# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d83802ff81a68ff078966b28464954e0a3d8911fea918c6a0b6dd8def8bd08c6060b8f8f6b45418bd76bc17c0bda504c2fe319e83e60b4a772ac7b68fb8881f0

test:
  secret_key_base: a9febd228e187137804f42003d3b77459f946f76f22ed80778151c534433d47934f0b54a3930792362e11acac4fe116eb295b699565a60f849cf0ad55eaa3627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
